name: tmind
description: A sample command-line application.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  excel: ^4.0.2
  intl: ^0.19.0
  sprintf: ^7.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
